# my global config
global:
  scrape_interval: 60s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 60s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["localhost:9090"]

# Scrape the Node Exporter
  - job_name: "node-exporter"
    scrape_interval: 60s
    static_configs:
      - targets: ["node-exporter:9100"]

# Scrape the em_accounts rails service
  - job_name: "em_accounts"
    scrape_interval: 60s
    static_configs:
      - targets: ["localhost:3000"]

